events {
    worker_connections 1024;
}

http {

    upstream authentication_service { # reference name
        server authentication-service:8000; # docker-container-name:port
    }

    upstream restaurant_service {
        server restaurant-service:8000;
    }

    upstream order_service {
        server order-service:8000;
    }

    upstream payment_service {
        server payment-service:8000;
    }

    server {
        listen 80; # runs at port 80 inside container

        location /api/authentication/ {
            proxy_pass http://authentication_service/;
        }

        location /api/restaurant/ {
            proxy_pass http://restaurant_service/;
        }

        location /api/orders/ {
            proxy_pass http://order_service/;
        }

        location /api/payment/ {
            proxy_pass http://payment_service/;
        }
    }
}